name: Deploy to EC2 Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: self-hosted
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3



      - name: Use system Python
        run: |
          python3.9 --version
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install -r requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Flask app
        run: |
          nohup python app.py > app.log 2>&1 &
