name: Deploy to EC2 Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: self-hosted
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3



      - name: Use system Python 3.9
        run: |
          sudo alternatives --install /usr/bin/python python /usr/bin/python3.9 1
          python --version
          pip3.9 install -r requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Flask app
        run: |
          nohup python app.py > app.log 2>&1 &
